framework:
    messenger:
        failure_transport: failed

        transports:
            meili:
                dsn: '%env(DOCTRINE_MESSENGER_TRANSPORT_DSN)%'
#                options:
#                    exchange:
#                        name: meili
#                    queues:
#                        meili: ~
                retry_strategy:
                    max_retries: 3
                    multiplier: 2

            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
#            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
#            Symfony\Component\Notifier\Message\ChatMessage: async
#            Symfony\Component\Notifier\Message\SmsMessage: async
#            App\Message\FetchComposer: async
            Survos\MeiliBundle\Message\BatchIndexEntitiesMessage: meili

            #            App\Message\ProcessPackage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
