framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
#            async:
#                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
##                options:
##                    exchange:
##                        name: async
##                    queues:
##                        async: ~
#                retry_strategy:
#                    max_retries: 3
#                    multiplier: 2
#            load_composer:
#                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
#                options:
#                    exchange:
#                        name: load_composer
#                    queues:
#                        load_composer: ~
#                retry_strategy:
#                    max_retries: 3
#                    multiplier: 2
            meili:
                dsn: '%env(DOCTRINE_MESSENGER_TRANSPORT_DSN)%'
#                options:
#                    exchange:
#                        name: meili
#                    queues:
#                        meili: ~
                retry_strategy:
                    max_retries: 3
                    multiplier: 2

#            doctrine_async:
#                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
#                options:
#                    use_notify: true
#                    check_delayed_interval: 60000
#                retry_strategy:
#                    max_retries: 3
#                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
#            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
#            Symfony\Component\Notifier\Message\ChatMessage: async
#            Symfony\Component\Notifier\Message\SmsMessage: async
#            App\Message\FetchComposer: async
            Survos\MeiliBundle\Message\BatchIndexEntitiesMessage: meili

            #            App\Message\ProcessPackage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
